# Basic Ubuntu and Docker setup Vagrantfile
#
# Weave Getting Started Guides
#

require 'fileutils'
require 'ipaddr'

Vagrant.require_version ">= 1.6.0"

VAGRANTFILE_API_VERSION = "2"
CONFIG = File.join(File.dirname(__FILE__), "config.rb")
SIMPLE_DOCKER_NGINX = File.join(File.dirname(__FILE__), "Dockerfile-simple-nginx")
SIMPLE_DOCKER_APACHE = File.join(File.dirname(__FILE__), "Dockerfile-simple-apache")
NGINX_CONF = File.join(File.dirname(__FILE__), "example/nginx.conf")
PHP_EXAMPLE = File.join(File.dirname(__FILE__), "example/index.php")
CHECK_WS = File.join(File.dirname(__FILE__), "example/check-ws.sh")

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

# Defaults for config options defined in CONFIG
#

$num_instances = 3
$instance_name_prefix = "weave-gs"
$share_home = false
$vm_gui = false
$vm_memory = 512
$vm_cpus = 1
$vm_starting_ip = "172.17.8.100"

if File.exist?(CONFIG)
    require CONFIG
end

$vm_ip = $vm_starting_ip

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "ubuntu/trusty64"
    config.ssh.insert_key = true

    if Vagrant.has_plugin?("vagrant-cachier")
        config.cache.scope = :box
    end

    (1..$num_instances).each do |i|
    
        config.vm.define vm_name = "%s-%02d" % [$instance_name_prefix, i] do |config|
            config.vm.hostname = vm_name
            if  i == 1 
                config.vm.network "forwarded_port", guest: 80, host: 8080
            end        

            ip = IPAddr.new($vm_ip)
            $vm_ip = ip.succ.to_s
            config.vm.network "private_network", ip: $vm_ip
        end
    end

    config.vm.provider :virtualbox do |vb|
        vb.gui = $vm_gui
        vb.memory = $vm_memory
        vb.cpus = $vm_cpus
    end

    config.vm.provision "docker" do |d|
        d.pull_images "ubuntu"
        d.pull_images "nginx"
        d.pull_images "weaveworks/weave"
        d.pull_images "fintanr/weave-gs-nginx-apache"
        d.pull_images "fintanr/weave-gs-nginx-simple"
    end
    
    config.vm.provision "shell", privileged: true, inline: <<-SHELL
        sudo curl -L git.io/weave -o /usr/local/bin/weave
        sudo chmod a+x /usr/local/bin/weave
    SHELL

    if File.exist?(SIMPLE_DOCKER_NGINX)
        config.vm.provision "shell", inline: "mkdir /home/vagrant/nginx-example; chown -R vagrant:vagrant /home/vagrant/nginx-example" 
        config.vm.provision "file", :source => "#{SIMPLE_DOCKER_NGINX}", :destination => "/home/vagrant/nginx-example/Dockerfile"
    end 
    
    if File.exist?(NGINX_CONF)
        config.vm.provision "file", :source => "#{NGINX_CONF}", :destination => "/home/vagrant/nginx-example/nginx.conf"
    end

    if File.exists?(SIMPLE_DOCKER_APACHE)
        config.vm.provision "shell", inline: "mkdir -p /home/vagrant/apache-php-example/example; chown -R vagrant:vagrant /home/vagrant/apache-php-example" 
        config.vm.provision "file", :source => "#{SIMPLE_DOCKER_NGINX}", :destination => "/home/vagrant/apache-php-example/Dockerfile"
    end 
    
    if File.exist?(PHP_EXAMPLE)
        config.vm.provision "file", :source => "#{PHP_EXAMPLE}", :destination => "/home/vagrant/apache-php-example/example/index.php"
    end
    
    if File.exist?(CHECK_WS)
        config.vm.provision "file", :source => "#{CHECK_WS}", :destination => "/home/vagrant/check-ws.sh"
    end
end
