# Basic Ubuntu and Docker setup Vagrantfile
#
# Weave Getting Started Guides
#

require 'fileutils'
require 'ipaddr'

Vagrant.require_version ">= 1.6.0"

VAGRANTFILE_API_VERSION = "2"
CONFIG = File.join(File.dirname(__FILE__), "config.rb")

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

# Defaults for config options defined in CONFIG
#

$num_instances = 1
$instance_name_prefix = "weave-rails"
$share_home = false
$vm_gui = false
$vm_memory = 512
$vm_cpus = 1
$vm_starting_ip = "172.17.8.100"

if File.exist?(CONFIG)
    require CONFIG
end

$vm_ip = $vm_starting_ip

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "ubuntu/trusty64"
    config.ssh.insert_key = true

    if Vagrant.has_plugin?("vagrant-cachier")
        config.cache.scope = :box
    end

    (1..$num_instances).each do |i|

        config.vm.define vm_name = "%s-%02d" % [$instance_name_prefix, i] do |config|
            config.vm.hostname = vm_name
            config.vm.network "forwarded_port", guest: 3000, host: 3000

            # just split out the ip
            #

            ip = IPAddr.new($vm_ip)
            $vm_ip = ip.succ.to_s
            config.vm.network :private_network, ip: $vm_ip 
        end
    end

    config.vm.provider :virtualbox do |vb|
        vb.gui = $vm_gui
        vb.memory = $vm_memory
        vb.cpus = $vm_cpus
    end

    # install docker packages
    #
    # https://docs.docker.com/installation/ubuntulinux/
    #

    config.vm.provision "shell", privileged: true, inline: <<-SHELL
        [ -e /usr/lib/apt/methods/https ] || {

            apt-get update
            apt-get install apt-transport-https
        }

        echo deb https://get.docker.com/ubuntu docker main > /etc/apt/sources.list.d/docker.list
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
        apt-get update
        apt-get install -y lxc-docker

        sudo wget -O /usr/local/bin/weave https://github.com/weaveworks/weave/releases/download/latest_release/weave
        sudo chmod a+x /usr/local/bin/weave
    SHELL

    # Pre-pull images to make running the examples faster
    config.vm.provision "docker", images: %w(
      weaveworks/weave
      weaveworks/weaveexec
      postgres
      ruby:2.2
      rails
      rails:onbuild
    )

end
