# Basic Ubuntu, Senenca, Node and Docker setup Vagrantfile
#
# Weave Getting Started Guides
#

require 'fileutils'
require 'ipaddr'

Vagrant.require_version ">= 1.6.0"

VAGRANTFILE_API_VERSION = "2"

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

# Defaults for config options defined in CONFIG
#

$num_instances = 2
$instance_name_prefix = "weave-gs"
$share_home = false
$vm_gui = false
$vm_memory = 512
$vm_cpus = 1
$vm_starting_ip = "172.17.8.100"

$vm_ip = $vm_starting_ip


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "ubuntu/trusty64"
    config.ssh.insert_key = true

    if Vagrant.has_plugin?("vagrant-cachier")
        config.cache.scope = :box
    end

    (1..$num_instances).each do |i|
    
        config.vm.define vm_name = "%s-%02d" % [$instance_name_prefix, i] do |config|
            config.vm.hostname = vm_name
            if  i == 1 
                config.vm.network "forwarded_port", guest: 80, host: 8080
            end        

            ip = IPAddr.new($vm_ip)
            $vm_ip = ip.succ.to_s
            config.vm.network "private_network", ip: $vm_ip
        end
    end

    config.vm.provider :virtualbox do |vb|
        vb.gui = $vm_gui
        vb.memory = $vm_memory
        vb.cpus = $vm_cpus
    end

    config.vm.provision "docker" do |d|
        d.pull_images "ubuntu"
        d.pull_images "docker"
        d.pull_images "weaveworks/seneca_user"
        d.pull_images "weaveworks/seneca_webapp"
        d.pull_images "weaveworks/seneca_offer"
    end
    
    config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
    
    config.vm.provision "shell", privileged: true, inline: <<-SHELL
        sudo -s curl -L git.io/weave -o /usr/local/bin/weave
        sudo chmod a+x /usr/local/bin/weave
    SHELL
end
