# Basic CentOS and Docker setup Vagrantfile
#
# Weave Getting Started Guides
#

require 'fileutils'
require 'ipaddr'

Vagrant.require_version ">= 1.6.0"

VAGRANTFILE_API_VERSION = "2"
CLOUD_CONFIG_PATH = File.join(File.dirname(__FILE__), "user-data")
CONFIG = File.join(File.dirname(__FILE__), "config.rb")
SIMPLE_DOCKER_HW = File.join(File.dirname(__FILE__), "Dockerfile-hw-centos")

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

# Defaults for config options defined in CONFIG
#

$num_instances = 2
$instance_name_prefix = "weave-gs"
$share_home = false
$vm_gui = false
$vm_memory = 1024
$vm_cpus = 1
$vm_starting_ip = "172.17.8.100"

if File.exist?(CONFIG)
    require CONFIG
end

$vm_ip = $vm_starting_ip

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "chef/centos-7.0"
    config.ssh.insert_key = true

    if Vagrant.has_plugin?("vagrant-cachier")
        config.cache.scope = :box
    end

    (1..$num_instances).each do |i|
    
        config.vm.define vm_name = "%s-%02d" % [$instance_name_prefix, i] do |config|
            config.vm.hostname = vm_name

            # just split out the ip
            #

            ip = IPAddr.new($vm_ip)
            $vm_ip = ip.succ.to_s
            config.vm.network "private_network", ip: $vm_ip 
        end
    end

    config.vm.provider :virtualbox do |vb|
        vb.gui = $vm_gui
        vb.memory = $vm_memory
        vb.cpus = $vm_cpus
    end

    # install docker packages
    #
    # https://docs.docker.com/installation/ubuntulinux/
    #

    config.vm.provision "shell", privileged: true, inline: <<-SHELL
        sudo yum -y install docker
        sudo systemctl start docker
        sudo systemctl enable docker
    SHELL

    # CentOS Sudoers file does not have /usr/local/bin in its path
    # by defualt
    #

    config.vm.provision "shell", privileged:true, inline: <<-SHELL
        sudo cat /etc/sudoers | sed "s|.*secure_path.*|&:/usr/local/bin|" > /tmp/sudoers.sed
        mv /tmp/sudoers.sed /etc/sudoers
    SHELL

    # for the purposes of our example we create a dockerfile to install apache

    if File.exist?(SIMPLE_DOCKER_HW)
        config.vm.provision "file", :source => "#{SIMPLE_DOCKER_HW}", :destination => "/home/vagrant/Dockerfile"
    end 
end
